#!/usr/bin/env bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."

alias c="clear"
alias g="git"
alias v="vim"
alias gp="git push && git push --tags"

alias ip="curl -s ipinfo.io/ip"
