#!/usr/bin/env bash



# General
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias c="clear"
alias v="vim"
alias g="git"
alias y="yarn"

# Java
alias j10="export JAVA_HOME=`/usr/libexec/java_home -v 10`; java -version"
alias j8="export JAVA_HOME=`/usr/libexec/java_home -v 1.8`; java -version"

# Git
alias gl="git pull"
alias gp="git push && git push --tags"
alias gcm="git commit -m"
alias gac="git add . && git commit -m"
alias gi="git init && gac 'Init'"
alias gca="git commit --amend --no-edit"
alias gb="git branch"
alias gc="git checkout"
alias gcb="git checkout -b"

# Other
alias notes="cd ~/notes && code ."
alias gh="chrome https://github.com"
alias rm-dstore="find . -name '.DS_Store' -type f -delete"